### ISSUE TITLE
_.sortBy([...], 'string', this); does not work in 3.10.1

### ISSUE THREAD

**Issue by ThisIsManta** [lodash/lodash#1530] opened 2015-10-14 14:07 UTC
```
_.sortBy(['a', 'ccc', 'bb'], 'length');
=> ["a", "bb", "ccc"]
```

Adding `this` as the third argument made `sortBy` function did nothing at all.
```
_.sortBy(['a', 'ccc', 'bb'], 'length', this);
=> ["a", "ccc", "bb"]
```

However, I was using version 2.4.1 and both mentioned statements worked perfectly.

Note that the later statement appears in *Backbone.js* inside `Collection.sort()` so that's the reason why I can't simply remove the third argument myself.

**Comment by jridgewell** [comment] 2015-10-14 14:46
That's caused by lodash's shorthand `_.matcher` syntax: `_.filter(col, 'prop', val)`. I think this has been resolved with https://github.com/jashkenas/backbone/pull/3732, which landed in Backbone v1.2.2.

**Comment by ThisIsManta** [comment] 2015-10-14 14:51
Ah! It seems like the time of upgrading *Backbone.js*. Thanks!

**Comment by jdalton** [comment] 2015-10-14 15:20
This has been resolved in v4 (edge master). Our prop shorthand is now an array of key/value pair and all methods have dropped the `thisArg` param.

**Closed by jdalton** 2015-10-14 15:20 UTC

**Comment by jridgewell** [comment] 2015-10-14 15:37
> Our prop shorthand for matchesProperty is now an array (key/value pair)

What does that look like?

**Comment by jdalton** [comment] 2015-10-14 15:39
```js
_.filter(objects, [key, prop]);
```

**Comment by jridgewell** [comment] 2015-10-14 15:40
Won't that conflict with deep properties?

**Comment by jdalton** [comment] 2015-10-14 18:21
Deep property shorthand is:
```js
_.filter(objects, { key1: value1, key2: value2 });
```

**Comment by jridgewell** [comment] 2015-10-14 18:23
But that's `_.matcher` shorthand...

**Comment by jdalton** [comment] 2015-10-14 19:05
Right (in lodash `_.matcher` is `_.matches`) so there's the `_.matches` shorthand and `_.matchesProperty` shorthand.

**Comment by jridgewell** [comment] 2015-10-14 19:07
But what's the deep property shorthand? `_.filter([{a: { b: true }}], ['a', 'b'])` now does `matchesProperty` (`obj.a === 'b'`).

**Comment by jdalton** [comment] 2015-10-14 20:16
There's `matches` and `matchesProperty` shorthands:
```js
var objects = [
  { 'a': { 'b': true },  'c': 'foo', 'd': 1 },
  { 'a': { 'b': true },  'c': 'bar', 'd': 0 },
  { 'a': { 'b': false }, 'c': 'foo', 'd': 1 }
];

// matchesProperty
_.filter(objects, ['c', 'bar']);
// => [{ 'a': { 'b': true },  'c': 'bar', 'd': 0 }]

_.filter(objects, ['a', { 'b': true }]);
// => [ { 'a': { 'b': true },  'c': 'foo', 'd': 1 }, { 'a': { 'b': true },  'c': 'bar', 'd': 0 }]

// matches
_.filter(objects, { 'a': { 'b': true }, 'd': 0 });
// [{ 'a': { 'b': true },  'c': 'bar', 'd': 0 }]
```

**Comment by jdalton** [comment] 2015-10-14 20:20
The `matchesProperty` shorthand is for the common case of matching a single property and value (think of the Underscore case) it avoids having to crawl the object to find the one key and value.
