### ISSUE TITLE
_.isNumber(NaN) === true

### ISSUE THREAD

**Issue by limonte** [lodash/lodash#1373] opened 2015-07-29 18:12 UTC
![](https://i.imgur.com/9IHX5Dc.png)

Feature or bug?

**Comment by megawac** [comment] 2015-07-29 18:19
Duplicate of a bunch of issues: https://github.com/jashkenas/underscore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+nan+isnumber

**Comment by jdalton** [comment] 2015-07-29 18:26
`NaN` is of the internal tag `Number` so `_.isNumber` returns `true`. Just as an invalid date object will still return `true` for `_.isDate`.

These methods don't validate the input they just determine if the value is of a specific tag.
You may be looking for [_.isFinite](https://lodash.com/docs#isFinite).

**Closed by jdalton** 2015-07-29 18:26 UTC
Labels: invalid

**Comment by limonte** [comment] 2015-07-30 13:23
@megawac @jdalton thanks for explanation! Sorry for not-searching before creating the issue :)

**Comment by msgoloborodov** [comment] 2017-09-08 16:12
But it is very unexpectedly. NaN is abbreviation of Not a Number. So isNumber(NotANumber) === true seems crazy.

**Comment by ephetic** [comment] 2017-09-08 16:24
```
> typeof NaN
"number"
```

`NaN`, `Infinity`, and `0.22` are all members of the type `Number`.  This isn't even unique to JavaScript.  `_.isFinite` gives you the behavior you want (a `Number` but not one of _those_ things).
