### ISSUE TITLE
Update array element at index

### ISSUE THREAD

**Issue by slorber** [lodash/lodash#2053] opened 2016-02-25 11:56 UTC
Hi,

I'd like to be able to update an object inside an array at a given index, in an immutable way.
I'm using lodash and ES6 and most of the time these 2 combined solves most of my problems except for this special case. I think it would be a nice addition to lodash as it already offers some array mutation helpers like _.without...

An ES6/7 implementation could look like:

```javascript
const updateArray = (array,index,updateFn) => {
  return [
  ...array.slice(0,index),
  updateFn(array[index]),
  ...array.slice(index+1)
  ];
}

const array = [ {x: "x1", y: "y1"} , {x: "x2", y: "y2"}, {x: "x3" , y: "y3"} ];
const arrayUpdated = updateArray(array,1,item => ({...item,x: "x updated"}));
console.log(arrayUpdated);
// [ {x: "x1", y: "y1"} , {x: "x updated", y: "y2"}, {x: "x3" , y: "y3"} ];
```

https://jsfiddle.net/dts30uk8/6/

**Comment by jfmengels** [comment] 2016-02-25 12:00
This looks like a duplicate of #1967.

**Comment by StreetStrider** [comment] 2016-02-25 12:54
```js
function update (array, index, fn)
{
  expect(index).within(0, array.length - 1)

  array = array.slice()
  array[index] = fn(array[index]) // since we do 1-to-1 map
  return array
}
```

**Comment by slorber** [comment] 2016-02-25 13:02
yes this is a duplicate or at least a subset of that `mapReplace` function.

Has it been implemented? I don't see it in the doc but the issue is closed

**Comment by jfmengels** [comment] 2016-02-25 13:06
It has not been implemented no. Feature requests are always closed so that they don't "pollute" the issues list, but are open for discussion. You can comment there and if there is sufficient traction, it will get implemented.

**Comment by slorber** [comment] 2016-02-25 13:22
Ok,


So what I can say, as a functional programmer using React, immutable data structures, ES6/7 and lodash, is that I'm missing this from lodash:

- Update item(s) inside an array of a given index or matching a predicate (this issue)
- Add items inside an array at a given index (somehow related to this issue)

Not really related to this issue but the only last thing i'm missing:

- Possibility to update deeply nested structures (something close to lenses):

```javascript
const deepObject = [ {a: "x1",b:"y1"}, {a: "x2",b:"y2"} ]

_.setIn(deepObject,[0,"a"],"newVal") => [ {a: "newVal",b:"y1"}, {a: "x2",b:"y2"} ]
_.updateIn(deepObject,[0,"a"],val => "newVal") => [ {a: "newVal",b:"y1"}, {a: "x2",b:"y2"} ]
_.deleteIn(deepObject,[0,"a"]) => [ {b:"y1"}, {a: "x2",b:"y2"} ]
```


Maybe all that is out of the scope of lodash? What I know is that I need these features to work with immutable values, and I don't like to use 15000 different FP libs, particularly having to use one with immutable vector tries as I'm perfectly fine with the performances of plain old JS objects as my lists/objects are not significantly big.

**Comment by jfmengels** [comment] 2016-02-25 13:29
That is an other existing feature request https://github.com/lodash/lodash/issues/1823 (again, issue is closed, but open for discussion) ;)
I'd suggest going to https://github.com/lodash/lodash/issues/1823 and #1967 and leaving a comment there. It will be easier for the maintainers to find out how much interest is shown.

> Maybe all that is out of the scope of lodash
I don't think so in this case, but anyway, don't be shy about proposing feature requests!

**Closed** 2016-02-25 15:35 UTC
Labels: duplicate

**Comment by bcherny** [comment] 2016-05-10 20:06
For now, I have this hanging around in my codebase:

```ts
_.mixin({
  replaceAt: <A>(arr: A[], n: number, replacement: A): A[] => {
    return arr.slice(0, n).concat(replacement).concat(arr.slice(n + 1))
  }
})
```

**Comment by lifuzu** [comment] 2017-07-13 23:42
array.slice(index, 1, replacement)

For example:
array = [{a:1}, {b:1}, {c:3}]
// replace {b:1} to {b:2}, index started from 0, so, {b:1}'s index is 1, put 1 as the index:
array.splice(1, 1, {b:2})
console.log(array)
// [{a:1}, {b:**2**}, {c:3}]

**Comment by hadalin** [comment] 2017-08-03 07:40
>in an immutable way

`array.splice(index, 1, replacement)` mutates the array.
