### ISSUE TITLE
try _.multiply(5.1, 100);

### ISSUE THREAD

**Issue by rexwang0128** [lodash/lodash#4778] opened 2020-05-14 09:31 UTC
Math methods don't resolve the precision problem

**Comment by illuminist** [comment] 2020-05-21 09:34
Also try `console.log(5.1 * 100)`, the result will be the same.

It's a limitation of IEEE-754 number format that JS is using, and also the error doesn't limit to JS.

[Example](https://stackoverflow.com/questions/8503157/ieee-754-floating-point-arithmetic-rounding-error-in-c-sharp-and-javascript )

**Comment by liang-louis** [comment] 2020-05-22 02:50
The calculation result of 99.66 * 10 is also wrong, and the accuracy is also in question

**Comment by daedalus28** [comment] 2020-05-29 16:19
Since this is the behavior of javascript itself (and all floating-point numbers regardless of language) and is not a lodash issue, so I think this is safe to close.

**Comment by liang-louis** [comment] 2020-05-31 09:21
> Since this is the behavior of javascript itself (and all floating-point numbers regardless of language) and is not a lodash issue, I think this is safe to close.

Excuse me.Isn't the lodash method designed to solve the problem of js floating point computing losing precision?This method does not solve the problem at present

**Comment by illuminist** [comment] 2020-06-01 06:17
That deviation is negligible. If you using that to measure distance from earth to moon, it should be a few millimeters off from 3e+5 kilometers. And IEEE-754 floating isn't design to be used with equality comparison. And lodash isn't designed to solve that issue either. If you want to trim the extra bit, you can round it to any digit by yourself, which mean you will lose some the precision anyway just to get a nice looking number.

**Comment by daedalus28** [comment] 2020-06-03 22:17
@liang-louis `_.multiply` is not designed to solve precision problems. If that isn't clear, maybe we can add a note to the docs.

**Comment by bnjmnt4n** [comment] 2020-08-14 15:49
Closing as a duplicate of many similar issues (#3666, https://github.com/lodash/lodash/issues/4870, etc.)

**Closed by bnjmnt4n** 2020-08-14 15:49 UTC
Labels: duplicate
