### ISSUE TITLE
Lang: isPromiseLike

### ISSUE THREAD

**Issue by dcherman** [lodash/lodash#1935] opened 2016-02-03 16:19 UTC
How would you feel about adding an `isPromiseLike` to the lang features of Lodash that duck types a value based on the definition in the Promise/A+ spec?

I've seen enough people write their own implementations of this that it might be worth it, especially since it is pretty minimal.  Thanks!

**Comment by StreetStrider** [comment] 2016-02-03 16:25
@dcherman, what's the use-case?

**Comment by dcherman** [comment] 2016-02-03 16:45
In my latest case, it's for use in some AngularJS code.  If the user returns a promise from an expression (basically a function if you're not familiar), then we want to add a class to a specific element in order to change the cursor from default to a loading/spinner until the promise resolves.

We want to do this with `isPromiseLike` versus using `.when` or `.resolve` and always coalescing to a Promise so that in the case where one is not provided, we don't add and immediately remove a class which can cause needles re-renders.

**Comment by StreetStrider** [comment] 2016-02-03 16:53
@dcherman that's really an interesting case. I've asked because I wanted to notice how the `.resolve` works, but you're already aware of it. :thumbsup:
Most often `Promise.resolve` eliminates cases when someone wants to distinct promise and non-promise values, creating two separate branches of almost identical logic.

**Comment by megawac** [comment] 2016-02-03 17:07
Possible duplicate of https://github.com/jashkenas/underscore/pull/1946 (see crossrefs).

**Comment by jdalton** [comment] 2016-02-03 17:21
@dcherman See https://github.com/lodash/lodash/pull/739#issuecomment-58844542. I'm not opposed a method like but lets nail down a name.

**Comment by jdalton** [comment] 2016-02-03 17:22
I guess `isPromiseLike` qualifies it enough :P

**Comment by jdalton** [comment] 2016-02-03 17:23
@dcherman are you up for a PR? (just modify lodash.js and add a test to test/test.js no need to generate docs)

**Comment by megawac** [comment] 2016-02-03 17:37
I think `isThenable` might be the best name

On Wed, Feb 3, 2016 at 12:23 PM, John-David Dalton <notifications@github.com

**Comment by phated** [comment] 2016-02-03 17:49
I'm on board with `isThenable` - `.then` being a function doesn't make something promise or necessarily promise-like.  If you were going to do something with `instanceof global.Promise` then `isPromiseLike` might make more sense.

**Comment by dcherman** [comment] 2016-02-03 19:19
I'm down to make a PR.  That said, @domenic made a good point in https://github.com/lodash/lodash/pull/739#issuecomment-58844542 that technically per the spec, you're supposed to only retrieve the `.then` function once in the case that you have an (imo) slightly nutty API that changes the return value of `.then` in a getter.

That could be alleviated by returning the `.then` function rather than a boolean which is still truthy, but that may be surprising since all of the other `isFoo` friends return booleans.

**Comment by jdalton** [comment] 2016-02-03 21:48
I'm not concerned with the getter side effects. We have an `_.isArrayLike` method which checks `.length` and that is what it is. Duck typing is as duck typing does.

**Comment by jdalton** [comment] 2016-02-04 04:36
Thanks all. If there's interest and a PR we'll go from there.

**Closed by jdalton** 2016-02-04 04:36 UTC
Labels: enhancement

**Comment by gajus** [comment] 2016-05-19 10:54
Anyone know why Q named this function `isPromiseAlike`? https://github.com/kriskowal/q/wiki/API-Reference#qispromisealikevalue (As opposed to `isPromiseLike`.)

**Comment by gajus** [comment] 2016-05-19 11:02
> 11:52	gajus	What is the reason this function is called "is promise alike" as opposed to "is promise like"? https://github.com/kriskowal/q/wiki/API-Reference#qispromisealikevalue
> 11:52	gajus	Whats the grammatical difference?
> 12:01	Ox0dea	gajus: It's an idiom you'll bump into now and again in CS, the derivation being from "lookalike".
> 12:02	gajus	so, isPromiseAlike more correct then isPromiseLike?
> 12:02	Ox0dea	Of course, we say "setlike", so it's not exactly justified.
> 12:02	Ox0dea	gajus: No, I think it was a bad choice, but not a "wrong" one.
> 12:02	gajus	Okay.

**Comment by jdalton** [comment] 2016-05-19 13:48
@gajus Ah good tidbit. I thought looking at it initially that it was related to Promises/A spec.

**Comment by SrBrahma** [comment] 2021-11-04 04:58
This is the only opened issue about it.

Ahm... Ok, there are possible flaws with the implementation, but there are very popular libs that does this.

Ex
https://github.com/sindresorhus/p-is-promise
https://www.npmjs.com/package/is-promise
https://github.com/sindresorhus/is/blob/main/source/index.ts

Instead of having to install an extra small lib for a simple and common functionality, couldn't lodash just include this? Just state that there is a very rare and very specific case that it may fail. In my years of JS I never had it nor have heard of anybody falling into it. Better a solution that one may fall into if very careless than no solution at all, in such common lib with such a variety of functions.

The following is how it's done by *sindre* in the first lib, with 7mi/week downloads. The second one is more popular but, as him says about the second one, 

> "Why not is-promise? That module checks for a thenable, not an ES2015 promise. This one is stricter."

```js
const isObject = value => value !== null &&
  (typeof value === 'object' || typeof value === 'function');

export default function isPromise(value) {
  return value instanceof Promise ||
    (
      isObject(value) &&
      typeof value.then === 'function' &&
      typeof value.catch === '
    );
}
```

**Comment by SrBrahma** [comment] 2021-11-09 22:21
@jdalton can you look this please? Thanks!

**Comment by samuelsd1** [comment] 2024-02-21 13:39
@jdalton Hey, can we add this to `lodash`?
In my opinion, this is relevant for modern javascript
