### ISSUE TITLE
BUG _.lowerCase('STRING-123') removes '-' from the result

### ISSUE THREAD

**Issue by duydnguyen07** [lodash/lodash#4819] opened 2020-06-15 15:48 UTC
Version: 4.17.15
**_.lowerCase('STRING-123')** will produce **string 123** while the expected behavior is **string-123**

**Comment by chasingSublimity** [comment] 2020-06-15 17:55
I'm happy to take a look at this and submit a PR.

**Comment by Chandler-Davidson** [comment] 2020-06-15 18:36
@duydnguyen07, `_.lowerCase` separates the string into words, `_.toLower` leaves the punctuation.

I was confused as well, https://lodash.com/docs/4.17.15#toLower.

**Comment by jalalazimi** [comment] 2020-06-15 20:18
Duplicate of #4802

**Comment by duydnguyen07** [comment] 2020-06-16 08:43
Thanks guys for the clarification. I will close this ticket now so that our discussion can be moved to #4802

**Closed** 2020-06-16 08:43 UTC
