### ISSUE TITLE
merge should not ignore empty array

### ISSUE THREAD

**Issue by vincentcr** [lodash/lodash#1313] opened 2015-07-02 13:34 UTC
```
_.merge({ x:1, a:[1,2,3]}, {y:0,a:[]})
```
yields:
```
{ x: 1,
  a: [ 1, 2, 3 ],
  y: 0 }
```

but it should be:
```
{ x: 1,
  a: [ ],
  y: 0 }
```

**Comment by jdalton** [comment] 2015-07-02 14:09
Hi @vincentcr! This is by design. When merging you're merging an empty array into another array which essentially melts it away. The empty array doesn't overwrite the old one. We know devs have opinions on how things should be merged which is why we allow a `customizer` callback to be provided. See the [_.merge](https://lodash.com/docs#merge) docs for usage.

**Closed by jdalton** 2015-07-02 14:09 UTC
Labels: invalid

**Comment by dtaub** [comment] 2017-09-11 18:54
For anyone who stumbles upon this in the future, the customizer argument has been removed from `_.merge` in 4.x. It's now in a separate function, [_.mergeWith](https://lodash.com/docs/4.17.4#mergeWith).

**Comment by marqu3z** [comment] 2018-01-17 15:18
Sorry but this is still a bug.
Since `_.merge({a: [1]}, {a: [2]})` does not produce `{a: [1,2]}` but `{a: [2]}` the default behaviour is to replace the entire object and not to do a `concat`.
I don't see why with an empty array it should not be replaced, and the result is the same of a concat operation. 
This seems something not related to the need of a customizer.

**Comment by jdalton** [comment] 2018-01-17 16:53
Hi @marqu3z!

The merge behavior of arrays is by design. Arrays are treated like objects so index values are merged and not appended to arrays. As @dtaub points out you can use [_.mergeWith](https://lodash.com/docs/#mergeWith) to get the behavior you want.

**Comment by marqu3z** [comment] 2018-01-17 17:32
Hi @jdalton 

Thanks for the explanation, i struggled i while but now it makes sense. 
The array are not replaced, but the indexes are.

```
_.merge({a: [1,2]}, {a: [3]}) // {a: [3,2]}
```
So the empty array cannot produce nothing.

Now i can use `_.mergeWidth` with the right awareness.

**Comment by Bastorx** [comment] 2018-02-27 11:12
`
.mergeWith(obj, src, function(obj, src) {
  if (!_.isNil(src)) {
    return src;
  }
  return obj;
});
`
