### ISSUE TITLE
_.partialRight along with _.curry function is not working as expected

### ISSUE THREAD

**Issue by harikrishnakanchi** [lodash/lodash#3145] opened 2017-05-07 04:25 UTC
When I tried to pass `_.partialRight` applied function to `_.curry`, arguments are not properly passed to original function. 
For example,
```
var fun = function(a, b, c) {
  console.log(a, b, c);
};
var part = _.partialRight(fun, "c");
part("a", "b"); // a b c
_.curry(part, 2)("a", "b"); // a b c
_.curry(part, 2)("a")("b"); // a c b but it should be "a b c"
```

In the above example look at last one's output. I believe the output should be `a b c` instead of `a c b`.
Same problem is there for `_.partial` function as well in 3x version (It got fixed in latest 4x version). Look at the below example,
```
var fun = function(a, b, c) {
  console.log(a, b, c);
};
var part = _.partial(fun, _, _, "c");
part("a", "b"); // a b c
_.curry(part, 2)("a", "b"); // a b c
_.curry(part, 2)("a")("b"); // a undefined c but it should be "a b c"
```
Because of this we are unable to use `_.partialRight` and `_.curry` together.

**Comment by harikrishnakanchi** [comment] 2017-05-07 04:33
@jdalton  is this a expected behavior for `_.partialRight` and `_.curry`? I have updated the issue description, please take a look at this.
Thanks.

**Comment by jdalton** [comment] 2017-05-07 04:40
Hi @harikrishnakanchi!

If the problem is fixed in v4, then great! Else you might check out [this query](https://github.com/lodash/lodash/search?p=1&q=curryRight&type=Issues&utf8=%E2%9C%93). I suspect one of the issues is similar to your own.

**Closed by jdalton** 2017-05-07 04:40 UTC
Labels: invalid

**Comment by harikrishnakanchi** [comment] 2017-05-08 05:57
Hi @jdalton,
I have gone through those results in that page provided by you.
But I still feel that this is something we can change to avoid bugs.
In my example,
```
var fun = function(a, b, c) {
  console.log(a, b, c);
};
var part = _.partialRight(fun, "c");
_.curry(part, 2)("a", "b"); // a b c
_.curry(part, 2)("a")("b"); // a c b but it should be "a b c"
```
Don't you think it should give the same output regardless of how it's been called? This behavior is enough to create bugs in codebases. Even I found out this behavior while debugging the bug in codebase.
I have one require module like this,
```
define("someModule", ["lodash"], function(_) {
  var add = function (a, b, c) { //some function where order of arguments matters
    return a * b + c;
  };
  
  var add2 = _.partialRight(add, 2);
  
  var add3 = _.partialRight(add, 3);
  
  return {
    "add2": add2,
    "add3": add3
  };
});
```
Now whoever uses this module, has to be very careful while using this module. If developer uses `_.curry` expecting that it's gonna pass the arguments with same order then it raises a bug. The only way to avoid this is developer has to look into the implementation of this module and figuring out that order of passing the arguments while currying it.

any thoughts?

**Comment by muralikrishna8** [comment] 2017-05-08 14:34
Rambda gets it right, when you do the same thing.
```javascript
var fun = function(a, b, c) {
  console.log(a, b, c);
};
var part = R.partialRight(fun, "c");
R.curry(part)("a", "b"); // a b c
R.curry(part)("a")("b"); // a b c
```

**Comment by muralikrishna8** [comment] 2017-05-08 15:08
It works fine in Ramda, I have expected the same result from **lodash** as well
```javascript
var fun = function(a, b, c) {
  console.log(a, b, c);
};
var part = R.partialRight(fun, "c");
R.curry(part)("a", "b"); // a b c
R.curry(part)("a")("b"); // a b c
```
