### ISSUE TITLE
The key is wrong during _.find

### ISSUE THREAD

**Issue by raymondsze** [lodash/lodash#2367] opened 2016-05-23 10:43 UTC
_.find({a:20,b:30}, (v,k) => console.log(k));

expected: a, b
result: 0, 1

**Comment by jfmengels** [comment] 2016-05-23 11:26
@raymondsze This seems to work fine on my end. What version of lodash are you using?

**Comment by MichaelBorde** [comment] 2016-05-23 11:28
@jfmengels Same error since v4.13.0.

**Comment by jfmengels** [comment] 2016-05-23 11:29
My bad. Works in `4.12`, not in `4.13`

**Comment by jfmengels** [comment] 2016-05-23 11:54
@jdalton Looks related to the changes made in https://github.com/lodash/lodash/commit/6d02a64c4787eb5c96b1c1f06badf982622986ee.

Not sure how to fix it, so I'll probably leav that up to you, but I've created tests reproducing the error (and some more tests that don't currently break) here https://github.com/jfmengels/lodash/tree/issue-2367. Feel free to use them, I can create a PR if you prefer, let me know.

**Comment by jdalton** [comment] 2016-05-23 15:39
Closed by https://github.com/lodash/lodash/commit/d4c539800ef7d65a57e787d4186ec0a33b83c3d2.

**Closed by jdalton** 2016-05-23 15:39 UTC
Labels: bug
