### ISSUE TITLE
assign's behavior when first argument is undefined

### ISSUE THREAD

**Issue by fenwick67** [lodash/lodash#1928] opened 2016-02-02 17:14 UTC
_.assign works in a confusing manner when the first argument is undefined

```
var x;

_.assign(x,{hello:"world"});
// → {hello:"world"}

x
// → undefined
```

The docs claim that the first argument is mutated and returned but that's not the case here, personally I was expecting x to be assigned to {hello:"world"}.  Not sure if this is the intended behavior.

**Comment by jfmengels** [comment] 2016-02-02 17:36
`assign` aims to look like `Object.assign`, which doesn't accept `x` to be undefined, so this looks to me like the intended behavior. Strictly speaking `undefined` is not a value that can be mutated. `x` can be reassigned, but not mutated.

**Comment by megawac** [comment] 2016-02-02 17:39
You can not modify javascript objects by value so it would be impossible to change the value of `x`.

Do `x = _.assign(...)`

**Closed by megawac** 2016-02-02 17:39 UTC

**Comment by fenwick67** [comment] 2016-02-02 18:02
Didn't think of that, thanks @megawac .

**Comment by ethanroday** [comment] 2017-01-26 21:00
Just ran into this as well (but with `null` instead of `undefined`. @megawac, shouldn't `_.assign` (and friends) throw an error in this case?

**Comment by jdalton** [comment] 2017-01-26 21:02
This behavior has changed to avoid this issue. @ethanroday make sure you're using the latest v4 release.

**Comment by ethanroday** [comment] 2017-01-26 21:07
Thanks, @jdalton.
(Incidentally, you may want to update the version of lodash running on lodash.com. I can repro this if I open a debugging console from https://lodash.com/docs.)

**Comment by jdalton** [comment] 2017-01-26 21:24
Make sure you clear you cache and try again. I was testing on lodash's doc site :P

**Comment by ethanroday** [comment] 2017-01-26 21:26
Update: Just updated to 4.17.4 in my project (using npm) and am still seeing the issue:
![image](https://cloud.githubusercontent.com/assets/896670/22350994/d59966ca-e3ca-11e6-8181-016bf5d5df69.png)
Something I'm missing?

**Comment by jdalton** [comment] 2017-01-26 21:29
Ah, I misunderstood what you're issue was. What you're seeing is a JS thing. We can't make an `null` or `undefined` reference into anything else. We can however return an object if you provide `null` or `undefined`.

**Comment by ethanroday** [comment] 2017-01-26 22:04
Understood. My suggestion is that `_.assign()` throw an error in those cases. Given that it is modeled off of `Object.assign`, isn't that the expected behavior?

**Comment by jdalton** [comment] 2017-01-26 22:38
Naw. I won't be throwing an error. Lodash tries very hard not to do that. If you want errors thrown use shims and built-ins. They'll give you tons.

**Comment by ethanroday** [comment] 2017-01-31 17:53
Haha okay.
Would appreciate a note in the documentation, though.
