### ISSUE TITLE
lodash/fp: _.map() iteratee for objects does not pass in key and collection

### ISSUE THREAD

**Issue by stephenlam** [lodash/lodash#2020] opened 2016-02-18 21:33 UTC
The iteratee is supposed to be passed (value, key, collection). However, when using lodash/fp I only see (value). Is this because the argument list is capped to one? What is the purpose of the capping?

**Comment by megawac** [comment] 2016-02-18 21:36
Dupe of https://github.com/lodash/lodash/issues/1945, https://github.com/lodash/lodash/issues/1781

**Closed by megawac** 2016-02-18 21:36 UTC
Labels: invalid

**Comment by jdalton** [comment] 2016-02-18 21:38
This is by design and covered by the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments) for capped iteratee args.

It is customizable though. You can use do:
```js
var convert = require('lodash/fp/convert');
var map = convert('map', require('lodash/map'), { 'cap': false });
```

**Comment by jdalton** [comment] 2016-02-18 21:45
> Is this because the argument list is capped to one?

Yes.

> What is the purpose of the capping

Capping makes composition easier by avoiding complications with optional params which hit the `key` and `collection` params.

**Comment by jdalton** [comment] 2016-04-12 19:05
In v4.7.0 we introduced the [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) method to simply things:
```js
var map = require('lodash/fp/map').convert({ 'cap': false });
```

**Comment by rwieruch** [comment] 2016-04-12 20:41
#b4cc4ed

**Comment by stephenlam** [comment] 2016-04-15 01:49
Thanks for the heads up!

**Comment by aaronyo** [comment] 2016-12-09 04:16
What about adding "mapIndexed" like in clojure (the iteratee would then be (val, index) => ...).

I'm avoiding "configure." I don't think others reading my code should have to be on the lookout for this kind of configuration to understand my code.

I guess the main reason to not add mapIndexed is that it doesn't fit in non-fp lodash (which may be a good reason). Is that it?

For now, I think I'll use fp.map((idx) => ..., fp.range(col.length));

**Comment by jdalton** [comment] 2016-12-09 05:08
You're free to abstract the converted form into its own module within your code.

**Comment by aaronyo** [comment] 2016-12-09 07:28
Yes, I will need to create my own "mapIndexed," I believe.

I think it's gonna be a bad scene, though, if folks start create their own slightly different versions of this function and everyone calls it "map." That's what seems to be encouraged by configuration -- leave the names the same but alter the behavior. I don't really want to look at someone else's code and see "marmaduke.map()" or worse, just "map()" and then have to trace the to definition. I'd rather see "fp.map" and be reasonably confident about what that is, as I've always been with _.map.

Also, that's why I'm throwing out the possibility of creating the one defacto version in this lovely, well known lib. :-)

(Maybe I'm just way off base, but is fp trying to hard to hew to an auto conversion of _?)
