### ISSUE TITLE
memoize doesn't behave correctly with multi-argument functions

### ISSUE THREAD

**Issue by gezakov** [lodash/lodash#4583] opened 2019-12-10 22:52 UTC
The lodash memoize function seems to only work correctly with single-argument functions. If it's a multi-argument function it just memoizes based on the first argument and ignores the remaining arguments.

```
const _ = require('lodash');
const g = _.memoize((a, b) => a + b)
console.log(g(1, 2))
console.log(g(1, 3))
console.log(g(1, 4))
```

I expect the output to be 3 4 5

The output with lodash is 3 3 3

 If this behavior is by design I would expect that the docs would mention that lodash's memoize implementation doesn't work with multi-argument functions.

**Comment by rafde** [comment] 2019-12-13 16:42
https://lodash.com/docs/4.17.15#memoize
> By default, the first argument provided to the memoized function is used as the map cache key.

If you need it to do more you have to provide your own resolver. An example of that would be nice

```js
const g = _.memoize((a, b) => a + b, (a, b) => a + '+' + b)
console.log(g(1, 2))
console.log(g(1, 3))
console.log(g(1, 4))
console.log(g(1, 2))
```

**Comment by bnjmnt4n** [comment] 2020-08-14 11:30
Duplicate of #2115 and #680.

**Closed by bnjmnt4n** 2020-08-14 11:30 UTC
