### ISSUE TITLE
 [4.17.16] Cannot find module 'lodash/fp' from 'fp.js'

### ISSUE THREAD

**Issue by sharan-salian** [lodash/lodash#4846] opened 2020-07-08 12:16 UTC
In one of the projects we are facing the issue latest @mathiasbynens 

Force the usage of lodash v4.17.15 solves the problem, so it seems to be a problem with v4.17.16

```js
const { isPlainObject, mapKeys, mapValues } = require('lodash/fp');

const mapKeysDeep = cb => obj =>
  Array.isArray(obj)
    ? obj.map(mapKeysDeep(cb))
    : isPlainObject(obj)
      ? mapValues(mapKeysDeep(cb))(mapKeys(cb)(obj))
      : obj;

module.exports = mapKeysDeep;
```

**Comment by mxschmitt** [comment] 2020-07-08 12:48
Duplicate of https://github.com/lodash/lodash/issues/4843

**Comment by stefcameron** [comment] 2020-07-08 15:29
This is a problem with 4.17.17 also.

**Comment by mathiasbynens** [comment] 2020-07-08 16:09
Please give `lodash@4.17.18` a try. Details here: https://github.com/lodash/lodash/issues/4837#issuecomment-655609600

**Closed by mathiasbynens** 2020-07-08 16:09 UTC
