### ISSUE TITLE
Add the `splitBy` function for arrays

### ISSUE THREAD

**Issue by bsurai** [lodash/lodash#4591] opened 2019-12-13 08:04 UTC
It splits an array on smaller arrays by conditions.

Using
```
const arr = [null, 'text', 34456, {}]
const [numbers, strings, other] = splitBy(arr, [isNumber, isString])
// numbers is [34456]
// strings is ['text']
// other is [null, {}]
```
Implementation
```
export const splitBy = <T>(items: T[], conditions: Condition[]): T[][] => {
  const initial: T[][] = [...map(conditions, () => []), []] // the last array for "others"

  return reduce(items, (acc, item) => {
    const ind = findIndex(conditions, check => check(item))
    ind > -1 ? acc[ind].push(item) : last(acc).push(item)
    return acc
  },
  initial)
}
```

**Comment by bnjmnt4n** [comment] 2020-12-21 10:57
Duplicate of #1379.

**Closed by bnjmnt4n** 2020-12-21 10:57 UTC
Labels: duplicate
