### ISSUE TITLE
fp/gt, fp/lt... should flip their arguments

### ISSUE THREAD

**Issue by renaudtertrais** [lodash/lodash#3050] opened 2017-03-10 13:29 UTC
I think the order should change in fp because as it is curried, it feels weird when you partially apply them:

```js
const isPositive = gt(0);
const isNegative = gt(0); // what ?

isPositive(2); // false <-- fails
isNegative(-2); // true <-- works but...
```

Other example with composition:

```js
const overlaps = x => compose(
  gt(0), // works if we use lt(0) but it seems weird when reading the code
  get('length'),
  intersection(castArray(x)),
  castArray
);

overlaps([1, 2])([2, 3]); // false --> should be true
overlaps(2)([2, 3]); // false --> should be true
```

Can test here: http://jsbin.com/kezohajujo/edit?js,console

**Comment by jdalton** [comment] 2017-03-10 16:07
Hi @renaudtertrais!

This is an area of some debate among FP libs. While I'm not 💯 against this I'm marking it as `wontfix` for now since argument order of `gt` and `lt` are lower of my list of things to tackle.

**Closed by jdalton** 2017-03-10 16:07 UTC
Labels: change, wontfix

**Comment by floriansimon1** [comment] 2017-03-30 09:22
In which cases does what's currently implemented in Lodash make sense? I was about to submit a duplicate of this ticket because I stumbled upon this behaviour today, and I found it super weird.

**Comment by renaudtertrais** [comment] 2017-03-30 09:31
I think it make sense when you are not using partial application:

`gt(2, 3)` feels more readable as `2 > 3` than `3 > 2`. 

The thing is that, as I said, when you use fp functions that mean that you want to use partial application. In the other case, you can simply use the default function gt/lt functions.

**Comment by floriansimon1** [comment] 2017-03-30 09:38
Ah, yes. Do you think it would be a good idea to have differentiated behaviours for that kind of function, where calling it with one argument would do what feels more natural, and calling it with two would give us what you expect?

AFAICT, this is unprecedented in Lodash but I think it would be a great improvement, even though I'm not quite sure it is worth the major version bump it would cause.
