### ISSUE TITLE
_.invoke falls if it tries to call not a function

### ISSUE THREAD

**Issue by deser** [lodash/lodash#2760] opened 2016-10-26 11:48 UTC
![developer tools - https___lodash com_sw js 2016-10-26 14 44 36](https://cloud.githubusercontent.com/assets/3010698/19724777/d3ae57d6-9b8a-11e6-9817-1ccbff8c1ed2.png)

So I expect that _.invoke doesn't fail if `a` is not a function. 
Frankly speaking I'd say invoke should behave like result except binding context to parent (which is bad and sad:( ). I can't understand why _.result needs to bind context to parent

**Comment by jdalton** [comment] 2016-10-26 15:12
Hi @deser!

While Lodash is forgiving for nullish values once you provide a value it will try to execute it. It looks like it's been that way for the last 7 years. With that in mind I'm closing this as by design.

**Closed by jdalton** 2016-10-26 15:12 UTC

**Comment by yankouskia** [comment] 2016-10-26 18:13
Hi, @jdalton!
Thank you for answer. But let me disagree with you :) 
I always rely on lodash as non-error helping library with many usefull methods. So it would be great to add some check for that case. As to me, it is very important feature for production projects, but, unfortunately, today we had issue with it.
Thank you.
