### ISSUE TITLE
_.map gets jacked up on objects with `length` property 

### ISSUE THREAD

**Issue by lubelski** [lodash/lodash#4921] opened 2020-09-08 01:23 UTC
```js
_.map({ a: 4, b: 5}, (val, key) => `${key}: ${val}`)
//  =>  ["a: 4", "b: 5"]

_.map({ a: 4, length: 5}, (val, key) => `${key}: ${val}`)
// => ["0: undefined", "1: undefined", "2: undefined", "3: undefined", "4: undefined"]
```

I assume this implementation of `map` works this way (as opposed to a for loop or whatever) for performance reasons. 

https://github.com/lodash/lodash/blob/master/map.js#L21-L22

using version `4.17.20`

**Comment by happy257** [comment] 2020-09-13 10:41
This is due to the isArrayLike function used by map. According to the docs: 

> Checks if `value` is array-like. A value is considered array-like if it's not a function and has a `value.length` that's an integer greater than or equal to `0` and less than or equal to `Number.MAX_SAFE_INTEGER`.

I see this is fixed in v5.

**Comment by bnjmnt4n** [comment] 2020-12-20 11:14
This is working as intended. Any object with a length method will be treated as an array.

**Closed by bnjmnt4n** 2020-12-20 11:14 UTC
Labels: invalid
