### ISSUE TITLE
Feature suggestion: _.mode and _.modeBy (statistics function)

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#2284] opened 2016-04-28 12:19 UTC
Since some math functions have been added recently I thought It may be useful to add a mode function.

I implemented one as a mixin (based on http://stackoverflow.com/a/18878650):

```js
_.mixin({
  modeBy: (collection, iteratee) => _
    .chain(collection)
    .countBy(iteratee)
    .toPairs()
    .maxBy(_.last)
    .head()
    // in this implementation string "undefined" is returned if iteratee returning 
    // non existing property is given
    .thru(value => value === 'undefined' ? undefined : value)
    .value(),
})
```
but it has its downsides.

I suggest this function might be added to lodash core.

My use case:
From collection of objects I need to get the most frequently occurring value of some property.

**Comment by Florian-R** [comment] 2016-04-28 12:20
Dupe of #2184

**Comment by jrencz** [comment] 2016-04-28 12:49
@Florian-R thanks for spotting that.

**Closed** 2016-04-28 16:20 UTC
Labels: duplicate
