### ISSUE TITLE
_.set does not set nested property if primitive-like already exists at some level

### ISSUE THREAD

**Issue by brokenalarms** [lodash/lodash#2558] opened 2016-08-02 23:40 UTC
```javascript
var obj = {foo: {}}
_.set(obj, 'foo', 'string')
// obj is {foo: 'string'}

_.set(obj, 'foo.bar', 'new deeper nested branch prop')
// expected: obj is {foo: {bar: 'new deeper nested branch prop'}}  
// obj remains {foo: 'string'} without warning that property could not be set.
```
Thanks!

**Comment by jdalton** [comment] 2016-08-02 23:49
This is actually by design but maybe it shouldn't be. It was so you could walk over primitives to get to their inherited properties and continue traversal. That seems pretty edge case though. If you'd like to create a PR to change this that would be rad. As is though I'm closing as `invalid` since it's technically by design.

**Closed by jdalton** 2016-08-02 23:49 UTC
Labels: invalid

**Comment by ds82** [comment] 2016-08-03 09:14
Even if thats by design, the function should not pretend that all is fine (-> no error) but the result is probably not what the user expected.

**Comment by jdalton** [comment] 2016-08-03 15:26
Lodash avoids erroring. It's a feature.
