### ISSUE TITLE
Since v4 defaultsDeep converts function property into object

### ISSUE THREAD

**Issue by akloeber** [lodash/lodash#1877] opened 2016-01-25 09:51 UTC
Starting with lodash v4 defaultsDeep converts a function property into an object which was not the case for v3.10.1:
```
var _ = require('lodash');
var o = {
  foo: function() {}
};
console.log(typeof _.defaults({}, o).foo);
console.log(typeof _.defaultsDeep({}, o).foo);
```

lodash v3.10.1:
```
function
function
```

lodash v4.0.0:
```
function
object
```

__Environment:__
lodash v4.0.0
node v4.2.2
Mac OS X 10.11.2

**Comment by demoneaux** [comment] 2016-01-25 11:06
HI @akloeber! This is a duplicate of #1783 and is fixed in lodash v4.1.0 which is in the process of being released.

**Closed by demoneaux** 2016-01-25 11:06 UTC
Labels: duplicate
