### ISSUE TITLE
_.defaultsDeep on 4.0.0 different behavior

### ISSUE THREAD

**Issue by jaumard** [lodash/lodash#1834] opened 2016-01-19 08:53 UTC
I have a problem with new version of _.defaultsDeep lodash@4.0.0

On previous version I can do this : 
```
let api = {
    controllers: {
      ViewController: class ViewController extends Controller{...}
    }
}
let newApi = {
    controllers: {
      DefaultController: class DefaultController extends Controller{...}
    }
}
_.defaultsDeep(api, newApi)
```
And final api have classes in it but with last version classes are convert to empty object :(

Here with the debugger : 
v3.10.1 : 
<img width="504" alt="capture d ecran 2016-01-19 a 09 51 58" src="https://cloud.githubusercontent.com/assets/2970449/12413912/75aba506-be92-11e5-81d8-b530a5e79ea5.png">
v4.0.0 : 
<img width="477" alt="capture d ecran 2016-01-19 a 09 52 31" src="https://cloud.githubusercontent.com/assets/2970449/12413915/7808057e-be92-11e5-928c-b46e03690a0a.png">

How can I fix this ?

**Comment by jdalton** [comment] 2016-01-19 09:13
I believe this is fixed in the edge master branch where at least the assigned value will be an instanceof `SwaggerController`.

The problem is we don't want sources to be augmented so we have to clone values. Once we hit the non-plain object we attempt to clone it using a technique similar to `Object.create(Object.getPrototypeOf(object))`.

Related to #1783.

**Closed** 2016-01-19 09:14 UTC
