### ISSUE TITLE
lodash.pick has different behaviour from _.pick (does not support dot in the path)

### ISSUE THREAD

**Issue by AntonBazhal** [lodash/lodash#4459] opened 2019-09-06 15:35 UTC
```javascript
const doc2 = {
  "source": {
    "name": "foo",
    "event": "bar",
    "data": {
      "businessUnit": {
        "name": "baz"
      }
    }
  }
};

const pick1 = require('lodash.pick');
const pick2 = require('lodash/pick');

console.log('lodash.pick:', pick1(doc2, [
  'source.name',
  'source.event',
  'source.data.businessUnit.name'
]));

console.log('lodash/pick:', pick2(doc2, [
  'source.name',
  'source.event',
  'source.data.businessUnit.name'
]));
```

Result:

```
lodash.pick: {}
lodash/pick: { source: { name: 'foo', event: 'bar', data: { businessUnit: [Object] } } }
```

**Comment by Mohit21GoJs** [comment] 2019-09-08 11:22
It is because lodash.pick uses [this](https://github.com/lodash/lodash/blob/4.4.0-npm-packages/lodash.pick/index.js#L155) logic, and as `source.name in  doc2` is false, if we use baseGet here then it will be fixed.

**Comment by Mohit21GoJs** [comment] 2019-09-08 11:24
@jdalton can i take up this one? this should probably be marked as bug in lodash.pick.

**Comment by jdalton** [comment] 2019-09-08 14:16
Oh sorry. This was recently patched on master branch.

**Comment by jdalton** [comment] 2019-09-08 14:18
Never mind. Mixed that up with a similar issue. Yes feel free to take it on

**Comment by Mohit21GoJs** [comment] 2019-09-08 17:43
> Never mind. Mixed that up with a similar issue. Yes feel free to take it on

for this i need to update the `npm-packages` branch right? since this does not seem to be in master branch, and this fix will ultimately be going into `npm-packages` branch itself.

**Comment by jdalton** [comment] 2019-09-08 21:27
You can target the 4.17.15-post branch

**Comment by Mohit21GoJs** [comment] 2019-09-09 06:29
> You can target the 4.17.15-post branch

@jdalton but the code in 4.17.15-post branch works fine, the issue is with lodash.pick npm package and hence we need to fix the branch and release the updated patch version for lodash.pick.

**Comment by jdalton** [comment] 2019-09-14 16:43
Ah okay! So this is just about cutting a new release for `lodash.pick`. I can do that, but keep in mind moving forward folks should really leverage the cherry-pickable modules of something like `lodash-es/pick`.

**Comment by Mohit21GoJs** [comment] 2019-09-14 20:20
@jdalton sure, you are right, but perhaps these issues are happening because the latest code in lodash.pick and lodash/pick are not in sync, and similarly for many other method modules, it might be worth noting because when as a package user, we expect lodash.pick to behave exactly same as lodash/pick :D

**Comment by thetutlage** [comment] 2019-12-26 09:33
Facing the same issue. The `lodash.pick` is way behind the implementation of `pick` exported by the complete module.

Can someone share, how to get the latest code without importing the entire package?

**Comment by AdamTyler** [comment] 2020-06-30 18:43
Any progress here? As @thetutlage said I would prefer not to import the entire package to make this work

**Comment by simonmarton** [comment] 2020-08-05 17:34
For anyone bumping into this, here's a working as expected `pick` with `lodash.zipobject` and `lodash.get`

```js
const pick = (obj, paths) =>
  zipObject(
    paths,
    paths.map((key) => get(obj, key))
  );
```

**Comment by blghns** [comment] 2020-11-10 04:22
@jdalton will loadash.pick (and packages in node modules branch) be deprecated since modules are cherry-pickable?

https://docs.npmjs.com/cli/v6/commands/npm-deprecate

looks like https://www.npmjs.com/package/lodash.pick wasn't updated for 4 years... Having 2 things doing the same thing is confusing 🤷

**Comment by noam7700** [comment] 2021-02-17 10:21
> For anyone bumping into this, here's a working as expected `pick` with `lodash.zipobject` and `lodash.get`
> 
> ```js
> const pick = (obj, paths) =>
>   zipObject(
>     paths,
>     paths.map((key) => get(obj, key))
>   );
> ```

nice! I used `lodash.zipobjectdeep` instead to fully copy pick behavior (to not flatten the original object properties)

**Closed** 2023-09-16 19:10 UTC
Labels: enhancement, issue bankruptcy
