### ISSUE TITLE
_.merge perform deep cloning of constructor function instances

### ISSUE THREAD

**Issue by SkReD** [lodash/lodash#2410] opened 2016-06-08 11:18 UTC
In 4.13 version, where i'll update from 3.10, suddenly all constructor instances, stored in object properties, began deeply cloning when call `_.merge`. For example

````
var instance = new SomeConstructor();
var sourceObj = { name: 'some_object', params: { param: instance }};
var destObj = {};

_.merge(destObj, sourceObj);

destObj.params.param == instance;//return false
````

I cant find any mentions in changelog that non-plain objects should be cloned in `_.merge`, so is it desired behaviour and i should adopt my code to it or it is a bug?

**Comment by jdalton** [comment] 2016-06-08 13:22
Hi @SkReD!

Cloning of source values is by design. Folks had complained that merged augmented their source values which was undesirable. Cloning of non-plain objects is tricky. Lodash will create an object that inherits from the same prototype. You can customize the merge behavior with [_.mergeWith](https://lodash.com/docs#mergeWith).

**Closed by jdalton** 2016-06-08 13:22 UTC
Labels: question

**Comment by SkReD** [comment] 2016-06-08 17:35
Thanks for reply, @jdalton!
And 

> Lodash will create an object that inherits from the same prototype

Yes)) I'll already see this in how my code began to work) Somehow all data models began cloning, but saving all prototype chains and methods. So code work as expected, but changes wont stored to the initial data models. It tooks me lot of time to figure out the source of problem) 

Maybe it is better not to merge such instances and theirs internals but simply overwrite them entirely in destination object?

**Comment by jdalton** [comment] 2016-06-08 19:06
> Maybe it is better not to merge such instances and theirs internals but simply overwrite them entirely in destination object?

That's where `_.mergeWith` comes in handy.

**Comment by SkReD** [comment] 2016-06-08 19:17
> That's where _.mergeWith comes in handy.
Yeah, but, maybe, it should be by default in `_.merge`, because it's strange that some class instance, that not designed for copying, is cloned and extended in the way, that developer dont even know. It may broke something, as in my case, were every class instance is tracked and there cannot be to instances with same identification fields.
I fix problem in my case, as you suggested, with `_.mergeWith`. But maybe in other frameworks problem appear again.

**Comment by sompylasar** [comment] 2016-10-04 17:17
The recently released `lodash@4.16.3` fixes this bug: the instances are now again assigned, not cloned during `merge`, according to the documentation. :+1: :tada: 
https://github.com/lodash/lodash/compare/4.16.2...4.16.3#diff-0874e5f9b48ed68be725d581f7d72647L3637

The regression comes from `lodash@4.4.0`.
https://github.com/lodash/lodash/compare/4.3.0...4.4.0#diff-0874e5f9b48ed68be725d581f7d72647R3153

Here's the fiddle that reproduces the issue: https://jsfiddle.net/f4fuksx1/1/

```js
// https://unpkg.com/lodash@4.0.0/lodash.js
// https://unpkg.com/lodash@4.3.0/lodash.js
// https://unpkg.com/lodash@4.4.0/lodash.js
// https://unpkg.com/lodash@4.5.1/lodash.js
// https://unpkg.com/lodash@4.6.1/lodash.js
// https://unpkg.com/lodash@4.16.2/lodash.js
// https://unpkg.com/lodash@4.16.3/lodash.js

function Foo() {
}

var fooInstance = new Foo();
var fooAtLevel0 = { fooProperty: fooInstance };
var fooAtLevel1 = { fooLevel1: { fooProperty: fooInstance } };

var fooAtLevel0Merged = _.merge({}, fooAtLevel0);
alert('fooAtLevel0Merged: ' + (fooAtLevel0Merged.fooProperty === fooInstance));
// With lodash@4.0.0: true
// With lodash@4.3.0: true
// With lodash@4.4.0: true
// With lodash@4.5.1: true
// With lodash@4.6.1: true
// With lodash@4.16.2: true
// With lodash@4.16.3: true

var fooAtLevel1Merged = _.merge({}, fooAtLevel1);
alert('fooAtLevel1Merged: ' + (fooAtLevel1Merged.fooLevel1.fooProperty === fooInstance));
// With lodash@4.0.0: true
// With lodash@4.3.0: true
// With lodash@4.4.0: false
// With lodash@4.5.1: false
// With lodash@4.6.1: false
// With lodash@4.16.2: false
// With lodash@4.16.3: true
```

**Comment by sompylasar** [comment] 2016-10-04 17:26
P.S. The documentation for `merge` clearly states that the behavior expected by the author of this ticket https://github.com/lodash/lodash/issues/2410#issuecomment-224668602 is correct.

> This method is like _.assign except that it recursively merges own and inherited enumerable string keyed properties of source objects into the destination object. Source properties that resolve to undefined are skipped if a destination value exists. **Array and plain object properties are merged recursively. Other objects and value types are overridden by assignment.**_ Source objects are applied from left to right. Subsequent sources overwrite property assignments of previous sources.

_(emphasis mine)_

**Comment by sompylasar** [comment] 2016-10-04 17:28
@jdalton Could you please add a test from https://github.com/lodash/lodash/issues/2410#issuecomment-251452860 so that this won't break again (won't start cloning non-plain-object models) without noticing?

**Comment by sompylasar** [comment] 2016-10-04 17:29
Refs https://github.com/lodash/lodash/issues/2676 https://github.com/lodash/lodash/issues/2702

**Comment by jdalton** [comment] 2016-10-04 17:29
Chill on the comment spam. Now.

**Comment by jdalton** [comment] 2016-10-04 17:30
You can edit your existing comments to add extra tid bits.

**Comment by jdalton** [comment] 2016-10-04 17:41
@sompylasar

While fixing an unrelated issue I noticed that by performing a deep clone I was by-passing the opportunity for the `customizer` to handle how those nested values are assigned. So instead I initiate a shallow clone then send the object through the recursive merge so that assignments are consistent and able to be customized.
