### ISSUE TITLE
Something wrong with 'reverse' in chain

### ISSUE THREAD

**Issue by eGavr** [lodash/lodash#1490] opened 2015-09-25 14:16 UTC
Use `lodash@3.10.1`.

Try to run this chain in node –>

```js
_([[1], [undefined], [3]])
    .take(2)
    .map(_.compact)
    .reverse()
    .value() // –> [ [ 3 ], [] ] – wrong!
```

Try to run this chain in browser –>

```js
_([[1], [undefined], [3]])
    .take(2)
    .map(_.compact)
    .reverse()
    .value() // –> [ [], [ 1 ]] – OK!
```

**Comment by jdalton** [comment] 2015-09-25 15:07
Wow. That's a great bug, as far as bugs go! The good news is it's fixed in our master branch. The bad news is I don't know why so I'll have to dig in a bit. I think this warrants a patch release though, so once I find it I'll publish a 3.10.2.

**Closed by jdalton** 2015-09-25 15:07 UTC
Labels: bug

**Comment by unlok** [comment] 2015-09-25 15:12
:+1:

**Comment by S-YOU** [comment] 2015-09-25 15:21
related? 
https://github.com/nodejs/node/issues/2507 
https://code.google.com/p/v8/issues/detail?id=4387#c18

**Comment by jdalton** [comment] 2015-09-25 16:52
@S-YOU thanks for the links, though I think the root cause is in lodash and not v8.
