### ISSUE TITLE
No compatible version found: lodash.upperfirst@^3.0.0

### ISSUE THREAD

**Issue by sgulseth** [lodash/lodash#2059] opened 2016-02-26 10:45 UTC
Hi,

It looks like lodash.upperfirst < 4.X has been unpublished from npm, I guess this is a mistake? 

Same thing happened earlier this year as well https://github.com/lodash/lodash/issues/1778
```
sch-bp-2733 :: ~ » npm view lodash.upperfirst

{ name: 'lodash.upperfirst',
  description: 'The lodash method `_.upperFirst` exported as a module.',
  'dist-tags': { latest: '4.1.2' },
  versions: [ '4.0.0', '4.0.1', '4.0.2', '4.1.0', '4.1.1', '4.1.2' ],
  maintainers:
   [ 'jdalton <john.david.dalton@gmail.com>',
     'mathias <mathias@qiwi.be>',
     'phated <blaine.bublitz@gmail.com>' ],
  time:
   { modified: '2016-02-16T09:42:50.146Z',
     created: '2016-01-13T11:19:21.380Z',
     '4.0.0': '2016-01-13T11:19:21.380Z',
     '4.0.1': '2016-01-26T08:59:33.345Z',
     '4.0.2': '2016-02-03T07:33:31.717Z',
     '4.1.0': '2016-02-08T02:32:55.566Z',
     '4.1.1': '2016-02-16T06:06:46.255Z',
     '4.1.2': '2016-02-16T09:42:50.146Z' },
  homepage: 'https://lodash.com/',
  keywords: [ 'lodash-modularized', 'upperfirst' ],
  repository: { type: 'git', url: 'git+https://github.com/lodash/lodash.git' },
  contributors:
   [ 'John-David Dalton <john.david.dalton@gmail.com> (http://allyoucanleet.com/)',
     'Blaine Bublitz <blaine@iceddev.com> (https://github.com/phated)',
     'Mathias Bynens <mathias@qiwi.be> (https://mathiasbynens.be/)' ],
  author: 'John-David Dalton <john.david.dalton@gmail.com> (http://allyoucanleet.com/)',
  bugs: { url: 'https://github.com/lodash/lodash/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '4.1.2',
  icon: 'https://lodash.com/icon.svg',
  scripts: { test: 'echo "See https://travis-ci.org/lodash/lodash-cli for testing details."' },
  dependencies: { 'lodash.tostring': '^4.0.0' },
  dist:
   { shasum: '64c8c48c3d47e10a45931bbaf635392e73a3a4a5',
     tarball: 'http://registry.npmjs.org/lodash.upperfirst/-/lodash.upperfirst-4.1.2.tgz' },
  directories: {} }
```

**Comment by jonXmack** [comment] 2016-02-26 10:53
Seconding this

    npm ERR! node v5.4.1
    npm ERR! npm  v3.3.12
    npm ERR! No compatible version found: lodash.upperfirst@^3.0.0
    npm ERR! Valid install targets:
    npm ERR! 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0

**Comment by squiddy** [comment] 2016-02-26 11:14
I might be wrong on this, I don't have much experience with npm & lodash, but:

How can lodash.capitalize@^3.0.0 even depend on lodash.upperfirst@^3.0.0, when according to the changelog of lodash, _.upperFirst was added at 4.0.0? 

https://github.com/lodash/lodash/wiki/Changelog#v400

**Comment by peebeebee** [comment] 2016-02-26 11:41
Same problem over here...

**Comment by AlaeddineMessadi** [comment] 2016-02-26 11:48
I have the same problem, this is the output 
```
npm ERR! notarget No compatible version found: lodash.upperfirst@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["4.0.0","4.0.1","4.0.2","4.1.0","4.1.1","4.1.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'lodash.capitalize'
npm ERR! notarget 

```

**Comment by attila** [comment] 2016-02-26 11:55
I've got the same problem. Is there a workaround for this?

**Comment by squiddy** [comment] 2016-02-26 11:56
@attila I've you did setup npm shrinkwrap, you can modify the dependencies.

Here at my work we haven't yet, that's why I forked the project we needed and modified the package.json (https://github.com/squiddy/sass-lint/commit/642aada3c1c71934e7632b09f0d0ee5ed11dac3f).

**Comment by kaigossel** [comment] 2016-02-26 11:58
Same problem here
```
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! No compatible version found: lodash.upperfirst@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0
```

**Comment by peebeebee** [comment] 2016-02-26 12:00
```
npm i --save lodash.upperfirst
npm shrinkwrap
npm i
```

**Comment by ChristianAuth** [comment] 2016-02-26 12:36
Same here.
the problem is that it seems like every project that references lodash is broken as of now. 
anyone found a workaround or do we need to wait for a new build?

**Comment by Draccoz** [comment] 2016-02-26 12:41
Everything started breaking... Guys, please fix it fast :(.

**Comment by peebeebee** [comment] 2016-02-26 12:44
This might work:

with...

- node 4.3.1
- npm 2.14.12

```
npm install --save lodash.upperfirst
npm shrinkwrap
npm i
```

**Comment by przemcio** [comment] 2016-02-26 13:00
Please be aware that  npm shrinkwrap will  not apply on dev dependecies. In such case you need to run

npm i --save-dev lodash.upperfirst
npm shrinkwrap --dev

**Comment by andyverbunt** [comment] 2016-02-26 14:11
Same problem here

**Comment by ilkkao** [comment] 2016-02-26 14:23
Please bring 3.x releases back!

**Comment by jdalton** [comment] 2016-02-26 15:16
Folks, this was in a rogue version of `lodash.capitalize` that got published. Nothing was unpublished.

**Comment by ghpabs** [comment] 2016-02-26 15:21
Thanks @jdalton. Everything seems fine now.

**Comment by larsha** [comment] 2016-02-26 15:30
I'm still having problems.

**Comment by jdalton** [comment] 2016-02-26 15:35
Just pushed the fix.

**Closed by jdalton** 2016-02-26 15:35 UTC
Labels: bug

**Comment by jdalton** [comment] 2016-02-26 16:13
Yay Friday fires!

**Comment by ghpabs** [comment] 2016-02-26 16:35
It's actually quite amazing you manage keeping this project at 0 issues. You must be really good at house-keeping.
