### ISSUE TITLE
fp/mergeWith from 4.3 to 4.5 exponentially slower, more memory usage

### ISSUE THREAD

**Issue by jacobp100** [lodash/lodash#2052] opened 2016-02-25 09:29 UTC
We have data in the form:

```
[
  { '1': [ DOMNode ], '25': [ DOMNode, DOMNode ] },
  { '1': [ DOMNode ] },
  ...
]
```

Where DOMNodes are xmldom elements. Previously, we used `reduce(mergeWith(concat))`. However, upon upgrading to to lodash 4.5, things that were previously taking less than a millisecond are taking now over a minute by the third pass of this function. Waiting longer causes Node to run out of memory. I suspect this is because of a deep clone, when it isn't needed.

**Comment by megawac** [comment] 2016-02-25 12:58
Most likely an issue of deep clone (I've noticed some perf issues with it as well).

Can you provide a repro case (snippet/jsbin/etc) for the issue?

**Comment by jdalton** [comment] 2016-02-25 15:32
Our clone methods should not attempt cloning DOM nodes. If they are then that's a bug.

**Comment by jdalton** [comment] 2016-02-25 15:45
Ah [xmldom](https://github.com/jindw/xmldom), so I bet they look like regular objects (unlike built-in dom).

**Comment by jdalton** [comment] 2016-02-25 15:47
I'm OK with merge being heavier but would like to avoid critical perf issues. If you have any suggestions of how to balance not mutating the source and this that would be great.

**Comment by jdalton** [comment] 2016-02-25 15:48
Maybe leave the source cloning to the fp flavor and pull it from lodash core?

**Comment by jdalton** [comment] 2016-02-25 16:43
I'm closing this as `invalid` because while not great it is by design. I'll kick around a change in behavior though.

**Closed** 2016-02-25 16:43 UTC
Labels: invalid

**Comment by jdalton** [comment] 2016-02-27 18:28
@jabclab I modified `baseMergeDeep` to avoid deep cloning if there's a customizer which should allow you to create a customized merge with `_.mergeWith`.

**Comment by jacobp100** [comment] 2016-02-29 08:27
Just following up on this: our use case is satisfied with (lodash/fp's) `assignWith`. Using that fixed our issue.

**Comment by jdalton** [comment] 2016-02-29 14:54
Cool! I think I should stress more in the documentation that `_.merge` is a deep recursive merge unlike `_.assign`, `_.extend`, `_.defaults` which are shallow.

**Comment by jdalton** [comment] 2016-02-29 19:00
Doc note added https://github.com/lodash/lodash/commit/2c5f026d3c59a38c429246513437681569b523b8.
