### ISSUE TITLE
Floor not rounding properly for 2 decimals

### ISSUE THREAD

**Issue by pootzko** [lodash/lodash#1478] opened 2015-09-21 08:59 UTC
Hi,

I found out that the `_.floor` has one case where it does not work properly:

```javascript
_.floor(4.1, 2)
// -> 4.09 (which is not expected - I would expect this to be 4.1)
```

where this is good:
```javascript
_.floor(4.11, 3)
// -> 4.11 (which is good)
```

I looked into the source code, and this is what gets executed:

```javascript
    function createRound(methodName) {
      var func = Math[methodName];
      return function (number, precision) {
          debugger;
        precision = precision === undefined ? 0 : (+precision || 0);
        if (precision) {
          precision = pow(10, precision);
          return func(number * precision) / precision;
        }
        return func(number);
      };
    }
```

what happens is that `number` is 4.1 and precision is `100` at the return inside `if`. Then `number * precision` is 409.99999999999994 (which should be 410 instead) and when you divide that by 100 you obviously get 4.09. So, I understand that this is really a JS problem with numbers with lots of decimals and I guess this is considered as "accepted" behavior by lodash (and it's not the kind of thing that lodash would handle)?

Cheers

**Comment by jdalton** [comment] 2015-09-21 15:23
I think this falls under "by design". I tried to think of a way to counter this (like doing a max compare between the result and the original number) but non panned out. \@thejameskyle.

**Comment by gibson042** [comment] 2015-09-21 15:49
@jdalton:
```patch
     function createRound(methodName) {
       var func = Math[methodName];
       return function(number, precision) {
         precision = precision === undefined ? 0 : (+precision || 0);
         if (precision) {
           precision = pow(10, precision);
-          return func(number * precision) / precision;
+          return func(round(number * precision)) / precision;
         }
         return func(number);
       };
     }
```

And if you want to get fancy, you can omit the redundant call from `_.round` by checking `methodName`.

**Comment by gibson042** [comment] 2015-09-21 16:10
Edit: The above breaks some negative-precision cases... better to use the algorithm at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor#Decimal_adjustment), which will handle everything modulo toString-based precision loss.

**Comment by jdalton** [comment] 2015-09-21 16:32
@gibson042 Are you up for a PR?

**Comment by gibson042** [comment] 2015-09-21 16:42
Sure, but I don't think I understand your git structure... where do I branch from, and what does the workflow look like?

**Comment by jdalton** [comment] 2015-09-21 16:53
Branch from master, update the lodash.js file, and add a test to test/test.js.

**Comment by jdalton** [comment] 2015-09-23 07:31
@gibson042 Any luck?

**Comment by gibson042** [comment] 2015-09-23 16:41
I'll probably start tomorrow. Expect a PR.

**Comment by jdalton** [comment] 2015-09-24 15:04
Moving to #1487.

**Closed by jdalton** 2015-09-24 15:04 UTC
Labels: bug
