### ISSUE TITLE
Bug in _.isEqual method

### ISSUE THREAD

**Issue by didiercrunch** [lodash/lodash#1859] opened 2016-01-21 15:10 UTC
Hi there,

I believe there is a bug in the `_.isEqual` method in lodash 4.0.0.  The returned value of `_.isEqual({a: 1, b: 2}, {b: 2, a: 1})` is `false`.  I have created a jsfiddle to demonstrate the issue https://jsfiddle.net/3qwu1zw1/3/.   I have tested the problem on firefox 43.0.4 and chrome  47.0.2526.106 using an ubuntu computer.

kind regards,

didier amyot

**Comment by megawac** [comment] 2016-01-21 15:20
Duplicate of https://github.com/lodash/lodash/issues/1758

**Closed by megawac** 2016-01-21 15:20 UTC
