### ISSUE TITLE
Doc version function was added

### ISSUE THREAD

**Issue by robcolburn** [lodash/lodash#1168] opened 2015-04-27 22:02 UTC
It would be nice to quickly know which version of lodash, a particular was added.  Sure, I'll find out eventually, but I'd like to quickly know "oh, I've already got this at my disposal", or "need to bump lodash version".

**Comment by jdalton** [comment] 2015-04-27 22:22
Hi @robcolburn! This is a duplicate of #993.

**Closed by jdalton** 2015-04-27 22:22 UTC

**Comment by robcolburn** [comment] 2015-04-27 22:24
Thanks!

On Monday, April 27, 2015, John-David Dalton <notifications@github.com>
wrote:

> Hi @robcolburn <https://github.com/robcolburn>! This is a duplicate of
> #993 <https://github.com/lodash/lodash/issues/993>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lodash/lodash/issues/1168#issuecomment-96837973>.
>


-- 
--
Rob Colburn
