### ISSUE TITLE
lodash/fp gt, gte, lt, lte not curried

### ISSUE THREAD

**Issue by andrewbranch** [lodash/lodash#1862] opened 2016-01-21 23:29 UTC
Not sure if it is intentional, or if there is good reason, but the math comparison functions are not curried by lodash/fp. Here is my attempt to figure out why, to no avail:

```js
import { add, gt } from 'lodash/fp';

// works like a charm
let addTen = add(10);
addTen(5); // 15

// does not work
let greaterThanFour = gt(4); // false. umm?
greaterThanFour(5); // error, because false is not a function, obviously

// let's try to see if we can figure out a reason why...
add.length; // 0, probably variadic?
add(1, 1, 1, 1, 1); // 2 nope
gt.length; // 2, makes sense, seems like you could curry that easily
```

**Comment by andrewbranch** [comment] 2016-01-21 23:30
(Using 4.0.0)

**Comment by billyjanitsch** [comment] 2016-01-21 23:40
Dupe of #1776.

**Closed** 2016-01-21 23:54 UTC
Labels: duplicate
