### ISSUE TITLE
_.sum does not return correct output for [null]

### ISSUE THREAD

**Issue by addnab** [lodash/lodash#4971] opened 2020-10-31 02:52 UTC
`_.sum([1, null, 0])` and `_.sum([null, null])` returns expected values while `_.sum([null])` returns `null`.

```js
> _.sum([])
0
> _.sum()
0
> _.sum('a')
'a'
> _.sum(null)
0
> _.sum([1, null, 0])
1
> _.sum([null])
null <--- should be 0
> _.sum([null, null])
0
```

**Comment by Semigradsky** [comment] 2020-11-21 22:29
You really think that it is a correct `sum` usage?

**Comment by radekmie** [comment] 2020-12-03 12:33
Same goes for `false` (and other falsy values).

**Comment by bnjmnt4n** [comment] 2020-12-20 16:12
Marking this as a duplicate of #4971.

**Closed by bnjmnt4n** 2020-12-20 16:12 UTC
