### ISSUE TITLE
_.group(array, amount)

### ISSUE THREAD

**Issue by Richienb** [lodash/lodash#4831] opened 2020-06-23 13:23 UTC
Like chunk but takes in the number of chunks to return to evenly distribute the items over.

```js
const _ = require("lodash")

_.group([1, 2, 3, 4, 5, 6], 3)
//=> [[1, 2], [3, 4], [5, 6]]

_.group([1, 2, 3, 4, 5], 2)
//=> [[1, 2, 3], [4, 5]]
```

**Comment by Doatti** [comment] 2020-06-28 13:16
I can't imagine this being used all that much. Either way, it's quite simple to implement using `_.chunk`:
```javascript
function group(array, amount) {
    return _.chunk(array, Math.ceil(array.length/amount));
}
```

**Comment by bnjmnt4n** [comment] 2020-12-21 14:21
Given that this is simple enough to compose from _.chunk with just a minimal addition, I'm closing this issue for now. That being said, we'll look at the [popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Closed by bnjmnt4n** 2020-12-21 14:21 UTC
Labels: enhancement, votes needed

**Comment by matthewvalentine** [comment] 2022-11-23 23:07
The problem is subtler than you'd expect, and so the solution @Doatti posted doesn't work and in fact `chunk` cannot be used to directly solve it. For example:
```javascript
f = (xs, a) => _.chunk(xs, Math.ceil(xs.length/a))

// Wrong number of groups
f([1,2,3,4,5,6], 4)
[ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ] ]

// Groups are not evenly sized
f([1,2,3,4,5,6,7,8,9,10], 4)
[ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ], [ 10 ] ]
```
Sometimes the answer requires a few of the buckets to be one size and the rest to be another. Because `chunk` always returns buckets of the same size (except maybe the last), it can't directly accomplish that.
