### ISSUE TITLE
defaultsDeep with different results for undefined properties

### ISSUE THREAD

**Issue by rplopes** [lodash/lodash#2676] opened 2016-09-26 17:28 UTC
Using `defaultsDeep`, `undefined` properties get filtered out when they're in the root level of the object, but not when they're nested. If `defaultsDeep` is meant to act recursively, shouldn't its rules be the same regardless of the nesting level?

To reproduce this issue:

```js
> _.defaultsDeep({}, { foo: undefined })
{}

> _.defaultsDeep({}, { bar: { foo: undefined } })
{ bar: { foo: undefined } }  // by the same rules, shouldn't it be `{ bar: {} }` ?
```

**Comment by jdalton** [comment] 2016-09-26 17:47
Hi @rplopes!

In this case since the initial property being written is `bar` and it doesn't exist on the destination object it's cloning the source object and assigning it. So currently by design. You raise an interesting point though. I'll look into it.

**Closed by jdalton** 2016-09-26 17:47 UTC
Labels: invalid
