### ISSUE TITLE
TypeError: stack.get is not a function

### ISSUE THREAD

**Issue by wizzfizz94** [lodash/lodash#4945] opened 2020-10-01 02:36 UTC
Occurs on lodash v4.17.20
## Code
```js
console.log(oldProfileConfig, newProfileConfig);
 if (!_.isEqual(oldProfileConfig, newProfileConfig)) {
  this.setProfileConfig(newProfileConfig);
}
```

## Log
```
{ onOffActive: false,
  onTime: 2020-10-01T09:00:00.000Z,
  offTime: 2020-09-30T21:00:00.000Z,
  dimSteps: [],
  scheduleDays: '1111111' } { onOffActive: false,
  onTime: 2020-10-01T09:00:00.000Z,
  offTime: 2020-09-30T21:00:00.000Z,
  dimSteps: [],
  scheduleDays: '1111111' }
[0-0] (node:14600) UnhandledPromiseRejectionWarning: TypeError: stack.get is not a function
    at equalObjects (/home/user/app/node_modules/lodash/core.js:1303:28)
    at baseIsEqualDeep (/home/user/app/node_modules/lodash/core.js:729:18)
    at baseIsEqual (/home/user/app/node_modules/lodash/core.js:664:12)
    at Function.isEqual (/home/user/app/node_modules/lodash/core.js:2660:12)
    at estimateCurrentScheduleDimLevel.then.dimLevel (/home/user/app/src/Devices/SmartLight/NASLightDevice.ts:642:24)
```

Can confirm issue resolved when downgrading to v4.17.19.

**Comment by FelixRilling** [comment] 2020-10-01 17:04
Can reproduce it.
The lines in question were introduced in 4.17.20: <https://github.com/lodash/lodash/compare/4.17.19...4.17.20>.

**Comment by acagastya** [comment] 2020-10-03 08:09
I can't seem to reproduce the issue with 4.17.19 and 4.17.20.  Is this already fixed?

**Comment by FelixRilling** [comment] 2020-10-03 10:03
@acagastya the issue only is present in the core build, the regular build does not have it.
Find an example here: https://codepen.io/FelixRilling/pen/xxVeKBQ?editors=1010

**Comment by falsyvalues** [comment] 2020-10-28 21:39
Hi @wizzfizz94!

This is duplicate of #4904.

**Closed by falsyvalues** 2020-10-28 21:39 UTC

**Comment by finfa** [comment] 2022-11-21 14:27
#4904 was deleted without solving the problem. This bug is still present in 4.17.21.

Please don't delete issues without solving them.

**Comment by latin-panda** [comment] 2023-01-17 04:30
#4904 wasn't resolved and it was deleted. I still experience the bug whenever upgrading to 4.17.21. 
Please reopen the issue.
