### ISSUE TITLE
lodash.com: Firefox blocks site due to SSL error

### ISSUE THREAD

**Issue by venning** [lodash/lodash#1108] opened 2015-04-05 01:42 UTC
This happens to a lot of sites, but Firefox is now blocking access to lodash.com due to not being able to validate the SSL cert completely.

Don't know if this is due to an intermediate server taking its time to update or what, just wanted to let you know FF users will only get an error message.

[See the error explained in an online SSL checker here](https://www.ssllabs.com/ssltest/analyze.html?d=lodash.com).

Screenshot of Firefox message:

![screen shot 2015-04-04 at 9 41 03 pm](https://cloud.githubusercontent.com/assets/3902717/6995388/5367ddb0-db13-11e4-92ea-abeddc669e05.png)

**Comment by jdalton** [comment] 2015-04-05 04:02
This is @mathiasbynens area of expertise. Any idea?

**Comment by dak0rn** [comment] 2015-04-05 07:56
This seems to be an issue with the Certificate Authority StartCom. Their certificate status responder returns *unknown* sometimes and Firefox then does not trust the certificate. 
This issue has already been discussed on [the Mozilla bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1006479).
As mentioned there, Chrome does not use OCSP to check the revocation state of a certificate. Thus, Chrome users won't get that error.

However, I tried it with Firefox 37.0.1 on OS X a couple of times and did not get an error.

**Comment by jdalton** [comment] 2015-04-05 15:44
The Mozilla bug redirects to [#1151270](https://bugzilla.mozilla.org/show_bug.cgi?id=1151270), which suggests the issue is related to newly issues certificates but that shouldn't be the case for our site.

**Comment by jdalton** [comment] 2015-04-05 15:51
I'm closing this for now as the issue with StartCom seems to be resolved.

**Closed by jdalton** 2015-04-05 15:51 UTC
Labels: documentation
