### ISSUE TITLE
Specials chars removed

### ISSUE THREAD

**Issue by lokomass** [lodash/lodash#4976] opened 2020-11-15 14:33 UTC
Hi,
3 years after, somes functions don't work...
_upperFirst or _startCase removed automatically specials chars....
"año" become "Ano".
Is it possible to makes this correct please ?

**Comment by pritam-patil** [comment] 2020-11-27 17:02
Removing non-ascii characters is probably understood but if input to `startCase` is `Mr. John`, it returns `Mr John`. Is it indeed expected? @jdalton @jashkenas

**Comment by OneHoopyFrood** [comment] 2023-08-09 22:34
Duplicate of #3383

**Closed** 2023-09-16 19:09 UTC
Labels: issue bankruptcy
